# Generated by Django 4.2.8 on 2024-04-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
