# Generated by Django 4.2.8 on 2024-03-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_semester_user_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
