# Generated by Django 4.2.8 on 2024-03-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_semester_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
