# Generated by Django 4.2.8 on 2024-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
