# Generated by Django 4.2.8 on 2024-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billuser_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='billuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='billuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
