# Generated by Django 4.2.8 on 2024-03-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_formulation', models.CharField(max_length=50)),
                ('question_moderation', models.CharField(max_length=50)),
                ('question_translation', models.CharField(max_length=50)),
                ('project_evaluation', models.CharField(max_length=50)),
                ('vivavoc_evaluation', models.CharField(max_length=50)),
                ('thesis_evaluation', models.CharField(max_length=50)),
                ('lab_exam_evaluation', models.CharField(max_length=50)),
                ('exam_committee_chairman', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('course_teacher_external', models.CharField(max_length=50)),
                ('number_of_tutorials', models.IntegerField()),
                ('total_tutorial_answerscript', models.IntegerField()),
                ('total_final_answerscript', models.IntegerField()),
                ('total_thesis_evaluation', models.IntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='billing.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='billing.semester'),
        ),
    ]
