# Generated by Django 4.2.8 on 2024-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_course_semester_courseinfo_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
