# Generated by Django 4.2.8 on 2024-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_evaluation_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Mahfuz', max_length=100),
        ),
    ]
