# Generated by Django 5.0.6 on 2024-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adress',
            field=models.CharField(default='Dhaka', max_length=123),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default='Professor', max_length=23),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='01334543666', max_length=30),
        ),
    ]
