# Generated by Django 4.2.7 on 2024-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_customuser_adress_alter_customuser_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default='Professor', max_length=23),
        ),
    ]
