# Generated by Django 4.2.7 on 2024-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_customuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bankaccno',
            field=models.CharField(default='12345678', max_length=50),
        ),
    ]
